import type {
  OfficeLocation,
  BatteryProject,
  CommunityMicrogrid,
  GlobeLocation,
  ArcData,
} from "./types";

export const offices: OfficeLocation[] = [
  {
    id: "office-seoul",
    name: "Seoul R&D Center",
    lat: 37.5665,
    lng: 126.978,
    city: "Seoul",
    country: "South Korea",
    type: "office",
    status: "Operational",
    function: "R&D",
    focus: "BESS Design & Prototyping, Systems Development",
    description:
      "Core research and development center driving battery energy storage system design, power electronics prototyping, and systems architecture.",
  },
  {
    id: "office-la",
    name: "Los Angeles Operations",
    lat: 34.0522,
    lng: -118.2437,
    city: "Los Angeles",
    state: "CA",
    country: "United States",
    type: "office",
    status: "Operational",
    function: "Operations",
    focus: "US Deployment, Integration, Field Services",
    description:
      "US headquarters managing deployment operations, system integration, and field services across North America.",
  },
];

export const batteryProjects: BatteryProject[] = [
  {
    id: "bess-desert-ridge",
    name: "Desert Ridge Storage",
    lat: 34.6868,
    lng: -118.1542,
    city: "Lancaster",
    state: "CA",
    country: "United States",
    type: "battery-storage",
    status: "Operational",
    capacityMW: 50,
    capacityMWh: 200,
    market: "Commercial & Industrial",
    commissioned: "2024-Q4",
    description:
      "Utility-scale battery storage facility supporting commercial and industrial peak shaving and grid services.",
  },
  {
    id: "bess-bayview",
    name: "Bayview Community Hub",
    lat: 37.8044,
    lng: -122.2712,
    city: "Oakland",
    state: "CA",
    country: "United States",
    type: "battery-storage",
    status: "Operational",
    capacityMW: 5,
    capacityMWh: 20,
    market: "Community Resilience",
    commissioned: "2025-Q1",
    description:
      "Community-scale storage hub providing backup power and resilience for underserved neighborhoods.",
  },
  {
    id: "bess-gulf-coast",
    name: "Gulf Coast Reserve",
    lat: 29.7604,
    lng: -95.3698,
    city: "Houston",
    state: "TX",
    country: "United States",
    type: "battery-storage",
    status: "Under Construction",
    capacityMW: 100,
    capacityMWh: 400,
    market: "Commercial & Industrial",
    commissioned: "2026-Q2",
    description:
      "Large-scale energy reserve supporting petrochemical corridor reliability and renewable integration.",
  },
  {
    id: "bess-great-plains",
    name: "Great Plains Wind Storage",
    lat: 35.222,
    lng: -101.8313,
    city: "Amarillo",
    state: "TX",
    country: "United States",
    type: "battery-storage",
    status: "Planned",
    capacityMW: 75,
    capacityMWh: 300,
    market: "Mobile Power",
    description:
      "Wind-paired storage system designed for rapid deployment and replication across the Texas panhandle.",
  },
  {
    id: "bess-peachtree",
    name: "Peachtree Grid Support",
    lat: 33.749,
    lng: -84.388,
    city: "Atlanta",
    state: "GA",
    country: "United States",
    type: "battery-storage",
    status: "Operational",
    capacityMW: 25,
    capacityMWh: 100,
    market: "Public Sector",
    commissioned: "2025-Q2",
    description:
      "Municipal grid support system providing frequency regulation and emergency backup for critical public infrastructure.",
  },
  {
    id: "bess-northeast",
    name: "Northeast Corridor Hub",
    lat: 40.7357,
    lng: -74.1724,
    city: "Newark",
    state: "NJ",
    country: "United States",
    type: "battery-storage",
    status: "Under Construction",
    capacityMW: 30,
    capacityMWh: 120,
    market: "Food & Grocery",
    commissioned: "2026-Q1",
    description:
      "Cold chain resilience hub ensuring uninterrupted power for food distribution and grocery logistics.",
  },
  {
    id: "bess-pacific-gateway",
    name: "Pacific Gateway Storage",
    lat: 21.3069,
    lng: -157.8583,
    city: "Honolulu",
    state: "HI",
    country: "United States",
    type: "battery-storage",
    status: "Planned",
    capacityMW: 15,
    capacityMWh: 60,
    market: "Community Resilience",
    description:
      "Island grid storage supporting Hawaii's 100% renewable energy mandate and community resilience goals.",
  },
];

// Baltimore Community Resilience Hub Program — 16-site microgrid network
export const baltimoreSites: CommunityMicrogrid[] = [
  {
    id: "balt-pathway",
    name: "Pathway Church of God",
    lat: 39.3143,
    lng: -76.5932,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 42,
    batteryKWh: 100,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Community resilience hub with rooftop solar and battery storage serving the surrounding neighborhood.",
  },
  {
    id: "balt-breath-of-god",
    name: "Breath of God",
    lat: 39.3015,
    lng: -76.6245,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 26,
    batteryKWh: 80,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Faith-based community hub providing emergency power and cooling services during grid disruptions.",
  },
  {
    id: "balt-city-of-refuge",
    name: "City of Refuge Baltimore",
    lat: 39.2876,
    lng: -76.6368,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 110,
    batteryKWh: 760,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Largest site in the Baltimore program with 110 kW solar and 760 kWh battery — anchor hub for west Baltimore resilience.",
  },
  {
    id: "balt-transformation",
    name: "Transformation Center",
    lat: 39.3054,
    lng: -76.5987,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 55,
    batteryKWh: 150,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Community center providing workforce training and emergency shelter, powered by on-site solar and storage.",
  },
  {
    id: "balt-franciscan",
    name: "Franciscan Center",
    lat: 39.2998,
    lng: -76.6148,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 43,
    batteryKWh: 100,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Social services hub supporting food distribution and community programs with resilient energy infrastructure.",
  },
  {
    id: "balt-liberty-grace",
    name: "Liberty Grace",
    lat: 39.3187,
    lng: -76.6512,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 38,
    batteryKWh: 80,
    solarInstallation: "Car Port",
    program: "Baltimore Community Resilience Hub",
    description:
      "Solar car port installation providing covered parking and resilient power for community services.",
  },
  {
    id: "balt-manna-house",
    name: "Manna House",
    lat: 39.2923,
    lng: -76.6043,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 37,
    batteryKWh: 80,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Community food pantry and services center with rooftop solar powering refrigeration and critical loads.",
  },
  {
    id: "balt-miracle-city",
    name: "Miracle City",
    lat: 39.2845,
    lng: -76.6290,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 110,
    batteryKWh: 380,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Large-scale community hub with substantial solar and storage capacity serving as a neighborhood anchor.",
  },
  {
    id: "balt-mt-sinai",
    name: "Mt Sinai",
    lat: 39.3098,
    lng: -76.6421,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 97,
    batteryKWh: 380,
    solarInstallation: "Car Port",
    program: "Baltimore Community Resilience Hub",
    description:
      "Solar car port deployment providing covered parking, EV charging readiness, and resilient backup power.",
  },
  {
    id: "balt-stillmeadow",
    name: "Stillmeadow Fellowship",
    lat: 39.3210,
    lng: -76.5875,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 97,
    batteryKWh: 380,
    solarInstallation: "Car Port",
    program: "Baltimore Community Resilience Hub",
    description:
      "Car port solar installation with large battery bank supporting emergency shelter operations and community events.",
  },
  {
    id: "balt-the-door",
    name: "The Door",
    lat: 39.2967,
    lng: -76.6178,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 34,
    batteryKWh: 80,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Youth and community services center with rooftop solar providing clean energy and backup power.",
  },
  {
    id: "balt-the-well",
    name: "The Well",
    lat: 39.2890,
    lng: -76.6085,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 40,
    batteryKWh: 100,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Community wellness center with solar and battery storage ensuring continuous operations during grid events.",
  },
  {
    id: "balt-cuof",
    name: "Center for Urban Families",
    lat: 39.2935,
    lng: -76.6312,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 52,
    batteryKWh: 150,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Family services center providing workforce development and community programs with resilient energy.",
  },
  {
    id: "balt-civic-works",
    name: "Civic Works",
    lat: 39.3076,
    lng: -76.5956,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 100,
    batteryKWh: 380,
    solarInstallation: "Car Port",
    program: "Baltimore Community Resilience Hub",
    description:
      "Environmental nonprofit with solar car port supporting green job training and community resilience.",
  },
  {
    id: "balt-harbel",
    name: "Harbel Community",
    lat: 39.3165,
    lng: -76.6089,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 77,
    batteryKWh: 150,
    solarInstallation: "Car Port + Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Mixed solar deployment with both car port and rooftop installations serving a large community center.",
  },
  {
    id: "balt-langston-hughes",
    name: "Langston Hughes",
    lat: 39.2856,
    lng: -76.6199,
    city: "Baltimore",
    state: "MD",
    country: "United States",
    type: "community-microgrid",
    status: "Contracted",
    solarKW: 77,
    batteryKWh: 150,
    solarInstallation: "Roof",
    program: "Baltimore Community Resilience Hub",
    description:
      "Cultural and community center with rooftop solar supporting arts programming and emergency services.",
  },
];

export const allLocations: GlobeLocation[] = [
  ...offices,
  ...batteryProjects,
  ...baltimoreSites,
];

// Connection arcs
export const arcs: ArcData[] = [
  {
    id: "arc-seoul-la",
    startLat: 37.5665,
    startLng: 126.978,
    endLat: 34.0522,
    endLng: -118.2437,
    label: "R&D \u2192 Operations",
  },
  {
    id: "arc-seoul-houston",
    startLat: 37.5665,
    startLng: 126.978,
    endLat: 29.7604,
    endLng: -95.3698,
    label: "R&D \u2192 Deployment",
  },
  {
    id: "arc-seoul-baltimore",
    startLat: 37.5665,
    startLng: 126.978,
    endLat: 39.2904,
    endLng: -76.6122,
    label: "R&D \u2192 Baltimore Program",
  },
];

// Aggregate stats
export const stats = {
  totalProjects: batteryProjects.length,
  totalCapacityMW: batteryProjects.reduce((sum, p) => sum + p.capacityMW, 0),
  totalCapacityMWh: batteryProjects.reduce((sum, p) => sum + p.capacityMWh, 0),
  operationalCount: batteryProjects.filter((p) => p.status === "Operational")
    .length,
  offices: offices.length,
  countries: new Set(allLocations.map((l) => l.country)).size,
  baltimoreSites: baltimoreSites.length,
  baltimoreSolarKW: baltimoreSites.reduce((sum, s) => sum + s.solarKW, 0),
  baltimoreBatteryKWh: baltimoreSites.reduce(
    (sum, s) => sum + s.batteryKWh,
    0
  ),
};
